package com.globant.example.dynamotest.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo {

	private String id;
	private String msrp;
	private String cost;
	private Long createTime;

	public ProductInfo() {
		this.createTime = System.currentTimeMillis();
	}

	public ProductInfo(String cost, String msrp) {
		this();
		this.msrp = msrp;
		this.cost = cost;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@DynamoDBAttribute
	public String getMsrp() {
		return msrp;
	}

	@DynamoDBAttribute
	public String getCost() {
		return cost;
	}

	@DynamoDBAttribute
	public Long getCreateTime() {
		return createTime;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setMsrp(String msrp) {
		this.msrp = msrp;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ProductID - ").append(id).append(" - Msrp: ").append(msrp)
				.append(" - Cost: ").append(cost);
		return sb.toString();
	}

	@Override
	public int hashCode() {
		if (id != null) {
			return id.hashCode();
		} else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj != null && obj instanceof ProductInfo) {
			ProductInfo other = (ProductInfo) obj;
			if(this.id == null && other.id == null) {
				return true;
			}
			if(this.id == null && other.id != null) {
				return false;
			}
			return this.id.equals(((ProductInfo) obj).getId());
		} else {
			return false;
		}
	}

}
